books = [
    {
        "book_id": "ebook_001",
        "title": "The Night Circus",
        "author": "Erin Morgenstern",
        "publisher": "Doubleday",
        "year": 2011,
    },
    {
        "book_id": "ebook_002",
        "title": "Amar Sonar Bangla",
        "author": "Rabindranath Tagore",
        "publisher": "Visva-Bharati",
        "year": 1924,
    },
    {
        "book_id": "ebook_003",
        "title": "Two States",
        "author": "Chetan Bhagat",
        "publisher": "Rupa Publications",
        "year": 2009,
    },
    {
        "book_id": "ebook_004",
        "title": "Sapiens: A Brief History of Humankind",
        "author": "Yuval Noah Harari",
        "publisher": "Harper",
        "year": 2011,
    },
    {
        "book_id": "ebook_005",
        "title": "Educated",
        "author": "Tara Westover",
        "publisher": "Random House",
        "year": 2018,
    },
    {
        "book_id": "ebook_006",
        "title": "The Alchemist",
        "author": "Paulo Coelho",
        "publisher": "HarperCollins",
        "year": 1988,
    },
    {
        "book_id": "ebook_007",
        "title": "Harry Potter and the Philosopher's Stone",
        "author": "J.K. Rowling",
        "publisher": "Bloomsbury Publishing",
        "year": 1997,
    },
    {
        "book_id": "ebook_008",
        "title": "1984",
        "author": "George Orwell",
        "publisher": "Secker & Warburg",
        "year": 1949,
    },
    {
        "book_id": "ebook_009",
        "title": "To Kill a Mockingbird",
        "author": "Harper Lee",
        "publisher": "J.B. Lippincott & Co.",
        "year": 1960,
    },
    {
        "book_id": "ebook_010",
        "title": "Pride and Prejudice",
        "author": "Jane Austen",
        "publisher": "T. Egerton, Whitehall",
        "year": 1813,
    },
    {
        "book_id": "ebook_011",
        "title": "Moby Dick",
        "author": "Herman Melville",
        "publisher": "Richard Bentley",
        "year": 1851,
    },
    {
        "book_id": "ebook_012",
        "title": "War and Peace",
        "author": "Leo Tolstoy",
        "publisher": "The Russian Messenger",
        "year": 1869,
    },
    {
        "book_id": "ebook_013",
        "title": "The Great Gatsby",
        "author": "F. Scott Fitzgerald",
        "publisher": "Charles Scribner's Sons",
        "year": 1925,
    },
    {
        "book_id": "ebook_014",
        "title": "One Hundred Years of Solitude",
        "author": "Gabriel García Márquez",
        "publisher": "Editorial Sudamericana",
        "year": 1967,
    },
    {
        "book_id": "ebook_015",
        "title": "The Catcher in the Rye",
        "author": "J.D. Salinger",
        "publisher": "Little, Brown and Company",
        "year": 1951,
    },
    {
        "book_id": "ebook_016",
        "title": "The Hobbit",
        "author": "J.R.R. Tolkien",
        "publisher": "George Allen & Unwin",
        "year": 1937,
    },
    {
        "book_id": "ebook_017",
        "title": "The Road",
        "author": "Cormac McCarthy",
        "publisher": "Alfred A. Knopf",
        "year": 2006,
    },
    {
        "book_id": "ebook_018",
        "title": "The Kite Runner",
        "author": "Khaled Hosseini",
        "publisher": "Riverhead Books",
        "year": 2003,
    },
    {
        "book_id": "ebook_019",
        "title": "Life of Pi",
        "author": "Yann Martel",
        "publisher": "Canongate Books",
        "year": 2001,
    },
    {
        "book_id": "ebook_020",
        "title": "A Brief History of Time",
        "author": "Stephen Hawking",
        "publisher": "Bantam Books",
        "year": 1988,
    },
]